#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

use crate::api::*;
use flutter_rust_bridge::*;

// Section: imports

// Section: wire functions

#[no_mangle]
pub extern "C" fn wire_manipulate_image(port_: i64, a: *mut wire_ManipulationInput) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "manipulate_image",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_a = a.wire2api();
            move |task_callback| manipulate_image(api_a)
        },
    )
}

// Section: wire structs

#[repr(C)]
#[derive(Clone)]
pub struct wire_list_photon_filter {
    ptr: *mut wire_PhotonFilter,
    len: i32,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_ManipulationInput {
    original_bytes: *mut wire_uint_8_list,
    filters: *mut wire_list_photon_filter,
    output_format: i32,
    quality: u8,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_PhotonFilter {
    name: *mut wire_uint_8_list,
    val1: i64,
    val2: i64,
    val3: i64,
    val4: i64,
    rgba: *mut wire_Rgba,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_Rgba {
    r: u8,
    g: u8,
    b: u8,
    a: u8,
}

#[repr(C)]
#[derive(Clone)]
pub struct wire_uint_8_list {
    ptr: *mut u8,
    len: i32,
}

// Section: wrapper structs

// Section: static checks

// Section: allocate functions

#[no_mangle]
pub extern "C" fn new_box_autoadd_manipulation_input() -> *mut wire_ManipulationInput {
    support::new_leak_box_ptr(wire_ManipulationInput::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn new_box_rgba() -> *mut wire_Rgba {
    support::new_leak_box_ptr(wire_Rgba::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn new_list_photon_filter(len: i32) -> *mut wire_list_photon_filter {
    let wrap = wire_list_photon_filter {
        ptr: support::new_leak_vec_ptr(<wire_PhotonFilter>::new_with_null_ptr(), len),
        len,
    };
    support::new_leak_box_ptr(wrap)
}

#[no_mangle]
pub extern "C" fn new_uint_8_list(len: i32) -> *mut wire_uint_8_list {
    let ans = wire_uint_8_list {
        ptr: support::new_leak_vec_ptr(Default::default(), len),
        len,
    };
    support::new_leak_box_ptr(ans)
}

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        if self.is_null() {
            None
        } else {
            Some(self.wire2api())
        }
    }
}

impl Wire2Api<String> for *mut wire_uint_8_list {
    fn wire2api(self) -> String {
        let vec: Vec<u8> = self.wire2api();
        String::from_utf8_lossy(&vec).into_owned()
    }
}

impl Wire2Api<ManipulationInput> for *mut wire_ManipulationInput {
    fn wire2api(self) -> ManipulationInput {
        let wrap = unsafe { support::box_from_leak_ptr(self) };
        (*wrap).wire2api().into()
    }
}

impl Wire2Api<Box<Rgba>> for *mut wire_Rgba {
    fn wire2api(self) -> Box<Rgba> {
        let wrap = unsafe { support::box_from_leak_ptr(self) };
        (*wrap).wire2api().into()
    }
}

impl Wire2Api<i64> for i64 {
    fn wire2api(self) -> i64 {
        self
    }
}

impl Wire2Api<Vec<PhotonFilter>> for *mut wire_list_photon_filter {
    fn wire2api(self) -> Vec<PhotonFilter> {
        let vec = unsafe {
            let wrap = support::box_from_leak_ptr(self);
            support::vec_from_leak_ptr(wrap.ptr, wrap.len)
        };
        vec.into_iter().map(Wire2Api::wire2api).collect()
    }
}

impl Wire2Api<ManipulationInput> for wire_ManipulationInput {
    fn wire2api(self) -> ManipulationInput {
        ManipulationInput {
            original_bytes: self.original_bytes.wire2api(),
            filters: self.filters.wire2api(),
            output_format: self.output_format.wire2api(),
            quality: self.quality.wire2api(),
        }
    }
}

impl Wire2Api<OutputFormat> for i32 {
    fn wire2api(self) -> OutputFormat {
        match self {
            0 => OutputFormat::Png,
            1 => OutputFormat::Jpeg,
            2 => OutputFormat::Gif,
            _ => unreachable!("Invalid variant for OutputFormat: {}", self),
        }
    }
}

impl Wire2Api<PhotonFilter> for wire_PhotonFilter {
    fn wire2api(self) -> PhotonFilter {
        PhotonFilter {
            name: self.name.wire2api(),
            val1: self.val1.wire2api(),
            val2: self.val2.wire2api(),
            val3: self.val3.wire2api(),
            val4: self.val4.wire2api(),
            rgba: self.rgba.wire2api(),
        }
    }
}

impl Wire2Api<Rgba> for wire_Rgba {
    fn wire2api(self) -> Rgba {
        Rgba {
            r: self.r.wire2api(),
            g: self.g.wire2api(),
            b: self.b.wire2api(),
            a: self.a.wire2api(),
        }
    }
}

impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
    fn wire2api(self) -> Vec<u8> {
        unsafe {
            let wrap = support::box_from_leak_ptr(self);
            support::vec_from_leak_ptr(wrap.ptr, wrap.len)
        }
    }
}

// Section: impl NewWithNullPtr

pub trait NewWithNullPtr {
    fn new_with_null_ptr() -> Self;
}

impl<T> NewWithNullPtr for *mut T {
    fn new_with_null_ptr() -> Self {
        std::ptr::null_mut()
    }
}

impl NewWithNullPtr for wire_ManipulationInput {
    fn new_with_null_ptr() -> Self {
        Self {
            original_bytes: core::ptr::null_mut(),
            filters: core::ptr::null_mut(),
            output_format: Default::default(),
            quality: Default::default(),
        }
    }
}

impl NewWithNullPtr for wire_PhotonFilter {
    fn new_with_null_ptr() -> Self {
        Self {
            name: core::ptr::null_mut(),
            val1: Default::default(),
            val2: Default::default(),
            val3: Default::default(),
            val4: Default::default(),
            rgba: core::ptr::null_mut(),
        }
    }
}

impl NewWithNullPtr for wire_Rgba {
    fn new_with_null_ptr() -> Self {
        Self {
            r: Default::default(),
            g: Default::default(),
            b: Default::default(),
            a: Default::default(),
        }
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

// Section: sync execution mode utility

#[no_mangle]
pub extern "C" fn free_WireSyncReturnStruct(val: support::WireSyncReturnStruct) {
    unsafe {
        let _ = support::vec_from_leak_ptr(val.ptr, val.len);
    }
}
