// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`.

// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors

import 'dart:convert';
import 'dart:typed_data';

import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'dart:ffi' as ffi;

abstract class ImageManipulation {
  Future<Uint8List> manipulateImage(
      {required ManipulationInput a, dynamic hint});

  Future<Uint8List> greyscaleImage(
      {required Uint8List originalBytes, dynamic hint});

  Future<String> checking({dynamic hint});
}

class ManipulationInput {
  final Uint8List originalBytes;
  final bool greyscale;
  final bool threshold;
  final int thresholdAmount;
  final OutputFormat outputFormat;
  final int quality;

  ManipulationInput({
    required this.originalBytes,
    required this.greyscale,
    required this.threshold,
    required this.thresholdAmount,
    required this.outputFormat,
    required this.quality,
  });
}

enum OutputFormat {
  Png,
  Jpeg,
  Gif,
}

class ImageManipulationImpl extends FlutterRustBridgeBase<ImageManipulationWire>
    implements ImageManipulation {
  factory ImageManipulationImpl(ffi.DynamicLibrary dylib) =>
      ImageManipulationImpl.raw(ImageManipulationWire(dylib));

  ImageManipulationImpl.raw(ImageManipulationWire inner) : super(inner);

  Future<Uint8List> manipulateImage(
          {required ManipulationInput a, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_manipulate_image(
            port_, _api2wire_box_autoadd_manipulation_input(a)),
        parseSuccessData: _wire2api_ZeroCopyBuffer_Uint8List,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "manipulate_image",
          argNames: ["a"],
        ),
        argValues: [a],
        hint: hint,
      ));

  Future<Uint8List> greyscaleImage(
          {required Uint8List originalBytes, dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_greyscale_image(
            port_, _api2wire_uint_8_list(originalBytes)),
        parseSuccessData: _wire2api_ZeroCopyBuffer_Uint8List,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "greyscale_image",
          argNames: ["originalBytes"],
        ),
        argValues: [originalBytes],
        hint: hint,
      ));

  Future<String> checking({dynamic hint}) =>
      executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => inner.wire_checking(port_),
        parseSuccessData: _wire2api_String,
        constMeta: const FlutterRustBridgeTaskConstMeta(
          debugName: "checking",
          argNames: [],
        ),
        argValues: [],
        hint: hint,
      ));

  // Section: api2wire
  int _api2wire_bool(bool raw) {
    return raw ? 1 : 0;
  }

  ffi.Pointer<wire_ManipulationInput> _api2wire_box_autoadd_manipulation_input(
      ManipulationInput raw) {
    final ptr = inner.new_box_autoadd_manipulation_input();
    _api_fill_to_wire_manipulation_input(raw, ptr.ref);
    return ptr;
  }

  int _api2wire_output_format(OutputFormat raw) {
    return raw.index;
  }

  int _api2wire_u32(int raw) {
    return raw;
  }

  int _api2wire_u8(int raw) {
    return raw;
  }

  ffi.Pointer<wire_uint_8_list> _api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  // Section: api_fill_to_wire

  void _api_fill_to_wire_box_autoadd_manipulation_input(
      ManipulationInput apiObj, ffi.Pointer<wire_ManipulationInput> wireObj) {
    _api_fill_to_wire_manipulation_input(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_manipulation_input(
      ManipulationInput apiObj, wire_ManipulationInput wireObj) {
    wireObj.original_bytes = _api2wire_uint_8_list(apiObj.originalBytes);
    wireObj.greyscale = _api2wire_bool(apiObj.greyscale);
    wireObj.threshold = _api2wire_bool(apiObj.threshold);
    wireObj.threshold_amount = _api2wire_u32(apiObj.thresholdAmount);
    wireObj.output_format = _api2wire_output_format(apiObj.outputFormat);
    wireObj.quality = _api2wire_u8(apiObj.quality);
  }
}

// Section: wire2api
String _wire2api_String(dynamic raw) {
  return raw as String;
}

Uint8List _wire2api_ZeroCopyBuffer_Uint8List(dynamic raw) {
  return raw as Uint8List;
}

int _wire2api_u8(dynamic raw) {
  return raw as int;
}

Uint8List _wire2api_uint_8_list(dynamic raw) {
  return raw as Uint8List;
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class ImageManipulationWire implements FlutterRustBridgeWireBase {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ImageManipulationWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ImageManipulationWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void wire_manipulate_image(
    int port_,
    ffi.Pointer<wire_ManipulationInput> a,
  ) {
    return _wire_manipulate_image(
      port_,
      a,
    );
  }

  late final _wire_manipulate_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_ManipulationInput>)>>('wire_manipulate_image');
  late final _wire_manipulate_image = _wire_manipulate_imagePtr
      .asFunction<void Function(int, ffi.Pointer<wire_ManipulationInput>)>();

  void wire_greyscale_image(
    int port_,
    ffi.Pointer<wire_uint_8_list> original_bytes,
  ) {
    return _wire_greyscale_image(
      port_,
      original_bytes,
    );
  }

  late final _wire_greyscale_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_uint_8_list>)>>('wire_greyscale_image');
  late final _wire_greyscale_image = _wire_greyscale_imagePtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_checking(
    int port_,
  ) {
    return _wire_checking(
      port_,
    );
  }

  late final _wire_checkingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_checking');
  late final _wire_checking =
      _wire_checkingPtr.asFunction<void Function(int)>();

  ffi.Pointer<wire_ManipulationInput> new_box_autoadd_manipulation_input() {
    return _new_box_autoadd_manipulation_input();
  }

  late final _new_box_autoadd_manipulation_inputPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_ManipulationInput> Function()>>(
      'new_box_autoadd_manipulation_input');
  late final _new_box_autoadd_manipulation_input =
      _new_box_autoadd_manipulation_inputPtr
          .asFunction<ffi.Pointer<wire_ManipulationInput> Function()>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list(
    int len,
  ) {
    return _new_uint_8_list(
      len,
    );
  }

  late final _new_uint_8_listPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list');
  late final _new_uint_8_list = _new_uint_8_listPtr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturnStruct(
    WireSyncReturnStruct val,
  ) {
    return _free_WireSyncReturnStruct(
      val,
    );
  }

  late final _free_WireSyncReturnStructPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
          'free_WireSyncReturnStruct');
  late final _free_WireSyncReturnStruct = _free_WireSyncReturnStructPtr
      .asFunction<void Function(WireSyncReturnStruct)>();

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();
}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

class wire_ManipulationInput extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> original_bytes;

  @ffi.Uint8()
  external int greyscale;

  @ffi.Uint8()
  external int threshold;

  @ffi.Uint32()
  external int threshold_amount;

  @ffi.Int32()
  external int output_format;

  @ffi.Uint8()
  external int quality;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Uint8 Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
